# $schema: https://json.schemastore.org/github-workflow.json

name: Check - Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

permissions: {}

jobs:
  build:
    name: Build
    uses: rbrownwsws/apko-workflows/.github/workflows/build.yaml@9f1faa31f756c00ddc47fbf9d9f865b73fdbbcff # master
    permissions:
      contents: read
