# $schema: https://json.schemastore.org/github-workflow.json

name: Check - Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

permissions: {}

jobs:
  build:
    name: Build
    uses: rbrownwsws/apko-workflows/.github/workflows/build.yaml@289910a074fd70c53a45dc42b0695f928658632d # master
    with:
      image-name: gghait
      image-tag: latest
    permissions:
      contents: read
