# $schema: https://json.schemastore.org/github-workflow.json

name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - apko.yaml
      - apko.lock.json

permissions: {}

jobs:
  build:
    name: Release
    uses: rbrownwsws/apko-workflows/.github/workflows/release.yaml@f397324c261ff96a561912086870c272621ed33d # v1.0.4
    permissions:
      contents: read            # to read the source needed to build the image
      id-token: write           # to get ID needed to sign attestations
      packages: write           # to store attestations
      attestations: write       # to store attestations
      artifact-metadata: write  # to store attestations
